### ISSUE TITLE
Cannot find module 'undefined', chunks.json not created in build folder after upgrading razzle to 4.1.0

### ISSUE THREAD

**Issue by zuhairkareem** [jaredpalmer/after.js#493]
## 🐛 Bug report
I get a build error when razzle version is upgraded to 4.1.0 from the basic example. chunks.json not created in build folder after upgrading razzle to 4.1.0

### Current Behavior

Error in the terminal on npm start
```
Cannot find module 'undefined'
    at webpackEmptyContext (/home/zuhair/Projects/project-test/src sync:2:1)
    at Module../src/server.js (/home/zuhair/Projects/project-test/build/webpack:/src/server.js:23:1)
    at __webpack_require__ (/home/zuhair/Projects/project-test/build/webpack:/webpack/bootstrap:691:1)
    at fn (/home/zuhair/Projects/project-test/build/webpack:/webpack/bootstrap:59:1)
    at Module../src/index.js (/home/zuhair/Projects/project-test/build/webpack:/src/index.js:3:1)
    at __webpack_require__ (/home/zuhair/Projects/project-test/build/webpack:/webpack/bootstrap:691:1)
    at fn (/home/zuhair/Projects/project-test/build/webpack:/webpack/bootstrap:59:1)
    at Object.0 (/home/zuhair/Projects/project-test/build/server.js:1514:1)
    at __webpack_require__ (/home/zuhair/Projects/project-test/build/webpack:/webpack/bootstrap:691:1)
    at /home/zuhair/Projects/project-test/build/webpack:/webpack/bootstrap:785:1

```

### Expected behavior

Should build without error and show the homepage

### Reproducible example

I have added the package.json with razzle & additional packages updated
https://github.com/zuhairkareem/razzle-afterjs-basic-example/blob/master/package.json

### Additional context
I have my project repo where I have integrated razzle 4.1.0. I want to add after.js for the routes showing api data.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| React            | 16.14
| After.js         | 3.1.3
| Razzle           | 4.1.0
| Node             | 14.16.0
| Browser          | Chrome 
| npm         | 6.14.13
| Operating System | Ubuntu 20.04

**Comment by nimaa77** [comment]
### Why you get this error?

the logic for generating `chunks.json` file was removed in razzle 4.
this is why after.js is not working with razzle 4.

### How to fix it?

Install the razzle plugin that contains the code for generating the related file.

[razzle-plugin-manifest](https://github.com/jaredpalmer/razzle/tree/master/packages/razzle-plugin-manifest)

install the plugin: `yarn add -D razzle-plugin-manifest`

create a new file in root directory of project (next to the package.json) called `razzle.config.js` and load plugin into razzle config:
```
// razzle.config.js

module.exports = {
  plugins: ['manifest'],
};
```
